# Generated by Django 3.1.1 on 2020-12-16 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=50)),
                ('class_batch', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_DOB', models.DateField()),
                ('employee_email', models.EmailField(max_length=50)),
                ('employee_phone', models.CharField(max_length=20)),
                ('employee_address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employement',
            fields=[
                ('employment_id', models.AutoField(primary_key=True, serialize=False)),
                ('employment_name', models.CharField(max_length=50)),
                ('employment_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Extracurricular',
            fields=[
                ('extracurricular_id', models.AutoField(primary_key=True, serialize=False)),
                ('extracurricular_name', models.CharField(max_length=50)),
                ('extracurricular_description', models.TextField(blank=True, null=True)),
                ('extracurricular_advisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('student_DOB', models.DateField()),
                ('student_email', models.EmailField(max_length=50)),
                ('student_phone', models.CharField(max_length=20)),
                ('student_address', models.TextField(blank=True, null=True)),
                ('student_class', models.ManyToManyField(to='app.Class')),
                ('student_extracurricular', models.ManyToManyField(to='app.Extracurricular')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_position',
            field=models.ManyToManyField(to='app.Employement'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employee'),
        ),
        migrations.AddField(
            model_name='class',
            name='class_subject',
            field=models.ManyToManyField(to='app.Subject'),
        ),
    ]
